databases:
  - name: otsumami-cooking
    databaseName: otsumami_cooking
    user: maru973
    region: singapore

services:
  - type: web
    name: otsumami-cooking
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false